# Dev docker-compose
version: "2.0"

services:
  scrapper:
    volumes:
      - ./scrapper:/scrapper
  mysql:
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tts
  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - 4000:80
    links:
      - mysql:db
  api:
    ## TODO: Add volume to avoid having to rebuild the api everytime
    #volumes:
      #- ./api:/api
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_PORT=3306