# Base docker-compose
version: "2.0"

services:
  scrapper:
    build: ./scrapper
    volumes:
      - ./scrapper:/scrapper
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
  api:
    build: ./api
    depends_on:
      - mysql
