# Prod docker-compose
version: "2.0"

services:
  scrapper:
    volumes:
      - ./scrapper:/scrapper
  mysql:
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tts
  api:
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_PORT=3306
